### PR TITLE
fix: converter cannot convert the data of tppos correctly

### PR DESCRIPTION
**Pull request by sakurawald**
Actually, the type of `tppos` is double. If you write an integer into the double type, then you get `0` always.

### CODE REVIEW

**Review by zly2006 — APPROVED** [review]
looks good

**Comment by zly2006** [comment]
well, loader version is better to be lower caz you dont know what version the players are using.

**Comment by disymayufei** [comment]
事实上，在我写这个Convertor的时候，zly2006还是用的int储存的坐标数据，之后改了储存方式后也就忽略了Convertor的问题

**Review by zly2006 — CHANGES_REQUESTED** [review]
loader version is better to be lower caz you dont know what version the players are using.

So maybe you should not modify this.

**Pull request merged**
